### ISSUE TITLE
EAValidator: filter by branch fails on PostgreSQL

### ISSUE THREAD

**Issue by rbertucat** [GeertBellekens/Enterprise-Architect-Toolpack#105]
Using EAValidator on PostgreSQL works well after I slightly adapted my SQL queries.

However, when changing the scope of the validation (e.g. by selecting a sub-package in the Scope section > Element), only the current package id is returned when executing the query, and not the whole tree. That means that when selecting a package of higher level in the tree, the validation does not occur on the enclosed packages.

It works well on the EAPX file (correct packageTreeIDString is returned).

https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/blob/6ff237112e23b2849143bf9c905684eb8d86ee7d/EAValidator/EAValidatorController.cs#L149

Somehow, I guess this is related to the [Package.cs method to resolve the package tree](https://github.com/GeertBellekens/Enterprise-Architect-Add-in-Framework/blob/939dfe49ae3bf0f59c06dec128ff3ed1099e2b92/EAAddinFramework/EAWrappers/Package.cs#L579).

**Comment by GeertBellekens** [comment]
Yes. The problem is probably related to casing in the database schema in PostgreSQL. The column t_package.Package_ID is lowercase in PostgreSQL t_package.pakage_id
That's probably the reason why `foreach (XmlNode packageIdNode in queryResult.SelectNodes("//Package_ID"))` is not working.

Solution might be to change the query to read
`select p.Package_ID as Package_ID from t_package...`

**Comment by rbertucat** [comment]
I can test it if you please provide the installer.

However, I'm not sure that's going to work. For EAValidator queries to work with PostgreSQL, I had to quote the table names in the SQL queries in the checks XML files, due to how PostgreSQL handles table names.

**Comment by GeertBellekens** [comment]
Here a new installer with this change
https://drive.google.com/open?id=1o7nCpeXybNyHVQAAvV39q2BTX_n6-9Bc
If this doesn't work I'll have to install PostgreSQL on development machine to test.

**Comment by rbertucat** [comment]
Thanks for the installer. Unfortunately, this version 2.0.13.27324 didn't fix the issue.

**Comment by GeertBellekens** [comment]
I'll install Postgres and debug...

**Comment by rbertucat** [comment]
I had to quote the column name actually and not the table name as I previously wrote to make my XML check files work:

> SELECT o.ea_guid AS "ItemGuid"

However, that does not seem to work with JET.

**Comment by GeertBellekens** [comment]
Found the problem.
I forgot to format the XPath. The method formatXPath sets it to lowercase for Postgres repositories.
`foreach (XmlNode packageIdNode in queryResult.SelectNodes(this.EAModel.formatXPath("//Package_ID")))`

Please try https://drive.google.com/open?id=1oAWG7E4JaQ5PvQnFkNRS24Fy6VSlobxk

**Comment by rbertucat** [comment]
works well, thanks! that fixed the issue.
