### ISSUE TITLE
EA TFS Connector - Sync fails with EA 10 & TFS 2018

### ISSUE THREAD

**Issue by shobanakrishna** [GeertBellekens/Enterprise-Architect-Toolpack#109]
Hello Geert,
Synchronization of work items either way, using EA TFS Connector is not working with TFS 2018. Please hint me if I'm missing something.
EA version: 10.0.1008
EAToolPack_Setup-v2.1.8.0

Error log for your reference: [EAAddinFramework.log](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/files/4557363/EAAddinFramework.log)

**Comment by GeertBellekens** [comment]
The line `Error Message: Method not found: 'System.String EA.IDualElement.get_FQStereotype()` indicates that you are using a version of EA that is too old. This version is not compatible with the EA Toolpack.

**Comment by shobanakrishna** [comment]
Oh ok Geert, thank you very much for the response!
What is the minimum version of EA compatible with EAToolPack?

**Comment by shobanakrishna** [comment]
Hello Geert,
Here is an update meanwhile: I tried with EA Version 14.1.1429 and TFS 2018, but doesn't work either. Requesting for your valuable inputs please. Thank you!

Error log for your ref: 
[EAAddinFramework.log](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/files/4559269/EAAddinFramework.log)

Error message on TFS => EA: 
![ErrorMessage](https://user-images.githubusercontent.com/48308154/80728823-001a5d00-8b25-11ea-8f16-f74764e787ae.PNG)

Sync result on EA => TFS: 
![SyncResult](https://user-images.githubusercontent.com/48308154/80728874-145e5a00-8b25-11ea-9abf-54be66ca8d6c.PNG)

**Comment by GeertBellekens** [comment]
I'm not sure. Probably version 12.1. You seem to be having an issue with the Json dll missing. I just tried, but I can't recreate the problem, I'm sorry.

**Comment by shobanakrishna** [comment]
Thank you Geert! I have got rid of the error with TFS => EA. 
But yet, synchronizing of work items is not successful. I will check again if I'm overlooking something.
Thanks again!
