### ISSUE TITLE
Mapping: Join expression not supported

### ISSUE THREAD

**Issue by robvadai** [GeertBellekens/Enterprise-Architect-Toolpack#111]
Symptoms:

1. Select the UML class from the Project view
2. Go to Specialize/Add-Ins/EA Mapping/Map
3. Click on any of the Source Model items (table or attributes)
4. Warning dialog shows

Warning dialog content:

```
DAO.Database [0x000000ce0]

Join expression not supported
```

This is when my target is a custom database driver (ie. not a built-in database like Oracle etc).

I'm using EA Mapping version 2.3.5.23639

**Comment by GeertBellekens** [comment]
Hi Rob, on what type of repository is that? (.eap, SQL Server, MySQL,...). If you open %appdata%\Sparx Systems\EA\dberror.txt you can see which query exactly was the reason for the error

**Comment by robvadai** [comment]
Yes, thanks for the advise, error is here:

```
28/03/2021 16:13:14
DAO.Database [0x00000ce0]

Join expression not supported.

Context:
	SQL: select fis.Object_ID  from (((((t_object o  inner join t_connector tr on (tr.Start_Object_ID = o.Object_ID         and  tr.Connector_Type = 'Abstraction'         and tr.Stereotype = 'trace')) inner join t_object o2 on (o2.Object_ID = tr.End_Object_ID       and o2.Name = o.Name       and o2.Object_Type = o.Object_Type)) inner join t_connector rel1 on (rel1.Start_Object_ID = o2.Object_ID       and rel1.Connector_Type in ('Realization', 'Realisation'))) inner join t_connector rel2 on (rel2.Start_Object_ID = rel1.End_Object_ID       and rel2.Connector_Type in ('Realization', 'Realisation'))) inner join t_object fis on fis.Object_ID = rel2.End_Object_ID) where o.ea_guid = '{BA49A127-32AA-40b1-9529-3A090FE8A960}' union select fis.Object_ID  from (((t_object o  inner join t_connector rel1 on (rel1.Start_Object_ID = o.Object_ID       and rel1.Connector_Type in ('Realization', 'Realisation'))) inner join t_connector rel2 on (rel2.Start_Object_ID = rel1.End_Object_ID       and rel2.Connector_Type in ('Realization', 'Realisation'))) inner join t_object fis on fis.Object_ID = rel2.End_Object_ID) where o.ea_guid = '{BA49A127-32AA-40b1-9529-3A090FE8A960}'
```

**Comment by GeertBellekens** [comment]
I see. That query works on SQL server, but it might not on other repository types.
You can change that query yourself in the settings:
![image](https://user-images.githubusercontent.com/615534/112764480-04871880-9009-11eb-8c98-047c200932c6.png)
If you are not using the contexts, you can change it to
`select 0 as test  from t_object`

**Comment by robvadai** [comment]
yes it's all good, thanks for the info

**Comment by robvadai** [comment]
What does this query is actually for?
