### ISSUE TITLE
Error during install msi installer version 2.3.17

### ISSUE THREAD

**Issue by arthur-edsn** [GeertBellekens/Enterprise-Architect-Toolpack#114]
Steps to repoduce:

- Install the plugin on a Windows 11 machine
- Check the EA Mesage composer and the EA addin Framework options. Disable other options
- Finish the installation
- Start EA
- Go to Specialize > EA Message Composer > Settings
- An error is shown (see screenshot below):

![image](https://user-images.githubusercontent.com/46195281/154672199-a1081d1b-e614-45a8-a7bf-ce165d4dee0b.png)

- The file IS created in the following folder with 0kb (no content)
C:\Users\[USERNAME]\AppData\Roaming\Bellekens\ECDMMessageComposer\{15643B50-A547-48b7-811E-95566E340B3B}.config

I tried to copy the config file of a collegae and paste the contents of this file inside the file shown above. 
When opening the settings screen (EA Message Composer) the same error is shown. The file is 0kb (content is whiped).

Hint from collegue with initials W.M.: The path %APPDATA%/Local/ should contain a Enterprise Architect Directory which is not available.

**Comment by GeertBellekens** [comment]
Fixed in version [2.3.18.0](https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/releases/tag/v2.3.18.0)
