### ISSUE TITLE
"Error: no «project» package found" should not occur in log

### ISSUE THREAD

**Issue by ArjanLoeffen** [GeertBellekens/Enterprise-Architect-Toolpack#49]
05-10-2016 01:22:29.303 diff: 15164,0106 ms Error: no «project» package found
is written to log. Should be dealt with differently; do not provide publish when no project available.

**Comment by GeertBellekens** [comment]
I'll check what is possible. I might be able to disable the function to publish if that doesn't affect performance too much.

**Comment by GeertBellekens** [comment]
problem solved by  disabling option to publish if no project package found. To be released in v1.2.3.0
