### ISSUE TITLE
Handle shared concept

### ISSUE THREAD

**Issue by GeertBellekens** [GeertBellekens/Enterprise-Architect-Toolpack#59]
Shared packages/elements/attributes/associations are not copied to the subset.
If the tagged value "shared" = true then the original is used and not a local copy of the subset.

**Comment by B-ITmabel** [comment]
Ik heb een account aangemaakt, kan je deze dan aan mij assignen?

**Comment by GeertBellekens** [comment]
Maarten,

Ik heb je uitgenodigd, maar ik denk dat jij nog moet aanvaarden:
[image: Inline image 1]
Zolang jij niet aanvaard hebt kan ik het issue niet aan jou toewijzen

Geert Bellekens


Sparx Systems Enterprise Architect consultant

Sparx Systems Value Added Reseller

geert@bellekens.com ⚫+32 (0)497 83 44 10 Weldadigheidsstraat 83 ⚫ 2540 Hove
⚫ Belgium

http://bellekens.com

**Comment by GeertBellekens** [comment]
solved in version 1.3.12
