### ISSUE TITLE
Fire Imvertor on packages with "imvertor" tagged value set

### ISSUE THREAD

**Issue by ArjanLoeffen** [GeertBellekens/Enterprise-Architect-Toolpack#66]
Allow imvertor to be available on all packages that have the taggged value "imvertor" set to "model". 

Currently imvertor is called on fixed stereotypes ""Basismodel" and ""Toepassing". This approach should be deprecated and removed in some future version.

Note
The Imvertor tagged value specifies that the package is a full model that can be processed by to the Imvertor software. This tagged value is required by the Imvertor extension (addin) on Enterprise Architect.

**Comment by GeertBellekens** [comment]
duplicate with https://github.com/GeertBellekens/Enterprise-Architect-Toolpack/issues/61
